[Unit]
# On vide les liens de dépendance qui causent le redémarrage
BindsTo=
PartOf=
After=network.target

[Service]
# On réinitialise pour passer du mode 'forking' au mode 'simple'
Type=simple
ExecStart=
# Commande directe sans le mode démon (-B) pour que systemd suive le processus
ExecStart=/usr/sbin/hostapd /etc/hostapd/hostapd.conf
